apiVersion: v1
kind: ConfigMap
metadata:
  name: gloco-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "mysql"
  DB_HOST: "gloco-db"
  DB_PORT: "3306"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  REDIS_HOST: "gloco-redis"
  REDIS_PORT: "6379"